# -*- coding: utf-8 -*-
"""Gasto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16IPbDvN0ObsNRJMD3KY2TtPC-_-rpinX
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Peso.py
# import numpy as np
# import streamlit as st
# import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LinearRegression
# 
# st.write("# Predicción de gasto de una actividad")
# st.image("c.jpg", caption="Predicción del costo de una actividad.")
# 
# st.header("Datos de la actividad")
# 
# def user_input_features():
# 
# 
#     Actividad = st.number_input(
#         "Actividad (por número):",
#         min_value=1,
#         max_value=10,
#         value=1,
#         step=1,
#     )
# 
#     Presupuesto = st.number_input(
#         "Presupuesto estimado (en pesos):",
#         min_value=0.0,
#         max_value=10000.0,
#         value=0.0,
#         step=50.0,
#     )
# 
#     Tiempo = st.number_input(
#         "Tiempo invertido en minutos:",
#         min_value=0,
#         max_value=300,
#         value=0,
#         step=5,
#     )
# 
#     Tipo = st.number_input(
#         "Tipo (1, 2 o 3):",
#         min_value=1,
#         max_value=3,
#         value=1,
#         step=1,
#     )
# 
#     Momento = st.number_input(
#         "Momento (1, 2 o 3):",
#         min_value=1,
#         max_value=3,
#         value=1,
#         step=1,
#     )
# 
#     Personas = st.number_input(
#         "Número de personas:",
#         min_value=1,
#         max_value=10,
#         value=1,
#         step=1,
#     )
# 
# 
#     user_input_data = {
#         "Actividad": Actividad,
#         "Presupuesto_num": Presupuesto,
#         "Tiempo invertido en minutos": Tiempo,
#         "Tipo": Tipo,
#         "Momento": Momento,
#         "No. de personas": Personas,
#     }
# 
#     features = pd.DataFrame(user_input_data, index=[0])
#     return features
# 
# 
# df = user_input_features()
# 
# 
# 
# datos = pd.read_csv("ActividadFinal.csv", encoding="latin-1")
# 
# 
# datos["Costo_num"] = (
#     datos["Costo"]
#     .astype(str)
#     .str.replace(r"[\$,]", "", regex=True)
#     .astype(float)
# )
# 
# datos["Presupuesto_num"] = (
#     datos["Presupuesto"]
#     .astype(str)
#     .str.replace(r"[\$,]", "", regex=True)
#     .astype(float)
# )
# 
# 
# X = datos[
#     [
#         "Actividad",
#         "Presupuesto_num",
#         "Tiempo invertido en minutos",
#         "Tipo",
#         "Momento",
#         "No. de personas",
#     ]
# ]
# y = datos["Costo_num"]
# 
# 
# 
# X_train, X_test, y_train, y_test = train_test_split(
#     X, y, test_size=0.30, random_state=1613726
# )
# 
# modelo = LinearRegression()
# modelo.fit(X_train, y_train)
# 
# 
# 
# prediccion = modelo.predict(df)[0]
# 
# st.subheader("Cálculo del costo")
# st.write(f"El costo estimado de la actividad es: **${prediccion:,.2f}** pesos")
#